package stack

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

// ReadEnv parses a .env file into a key→value map.
// Lines starting with # are ignored. Blank lines are ignored.
// Values may optionally be quoted with double-quotes.
func ReadEnv(path string) (map[string]string, error) {
	f, err := os.Open(path) // #nosec G304 — path is always within /opt/sur/stacks/<id>/.env
	if err != nil {
		return nil, err
	}
	defer f.Close()

	env := make(map[string]string)
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		idx := strings.IndexByte(line, '=')
		if idx < 0 {
			continue
		}
		key := strings.TrimSpace(line[:idx])
		val := strings.TrimSpace(line[idx+1:])
		// Strip optional surrounding double-quotes.
		if len(val) >= 2 && val[0] == '"' && val[len(val)-1] == '"' {
			val = val[1 : len(val)-1]
		}
		env[key] = val
	}
	return env, scanner.Err()
}

// WriteEnv writes the provided key→value map to a .env file, one KEY=VALUE per line.
// Existing file is overwritten. Mode 0600 to protect secrets.
func WriteEnv(path string, env map[string]string, fields []ConfigField) error {
	var sb strings.Builder
	sb.WriteString("# Generated by sur — do not edit manually unless you know what you are doing.\n")
	sb.WriteString("# Use 'sudo sur stack' to edit configuration safely.\n\n")

	for _, f := range fields {
		key := envKey(f.ID)
		val := env[key]
		if val == "" {
			val = f.Default
		}
		comment := fmt.Sprintf("# %s (%s)", f.Label, string(f.Type))
		sb.WriteString(comment + "\n")
		sb.WriteString(fmt.Sprintf("%s=%s\n\n", key, val))
	}

	return os.WriteFile(path, []byte(sb.String()), 0o600) // #nosec G306
}

// EnvFromConfig builds an env map from config fields and their resolved values.
// values maps field ID → user-provided value. Falls back to field Default.
func EnvFromConfig(fields []ConfigField, values map[string]string) map[string]string {
	env := make(map[string]string, len(fields))
	for _, f := range fields {
		key := envKey(f.ID)
		if v, ok := values[f.ID]; ok && v != "" {
			env[key] = v
		} else {
			env[key] = f.Default
		}
	}
	return env
}

// envKey converts a field ID (e.g. "bind_host") to an env var name ("BIND_HOST").
func envKey(id string) string {
	return strings.ToUpper(strings.ReplaceAll(id, "-", "_"))
}
